version: '3.7'
services:
  web:
    image: php:8.2-apache
    container_name: php8.2-apache
    volumes:
      - "./src:/var/www/html"
    ports:
      - 80:80
      - 443:443
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: delivery_database
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PHA_HOST=db
      - PHA_PORT=3306