
version: "3.8"
services:
    # Application
    app:
        build:
            context: ./docker/services/app
            dockerfile: app.dockerfile
        working_dir: /var/www
        env_file: .env
        volumes:
            - ./:/var/www
        networks:
            - ds-network

    # Web Server
    web:
        build:
            context: ./docker/services/web
            dockerfile: web.dockerfile
        working_dir: /var/www
        restart: always
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        networks:
            - ds-network

    # Database
    database:
        image: mysql:8.0.25
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: delivery
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            # MYSQL_USER: secret
            # MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        networks:
            - ds-network
networks:
    ds-network:
        name: "delivery-service-network"